### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jahaniam** [dataplayer12/swish-activation#1]
Thanks for sharing. I keep getting error for CIFAR10 dataset in this line:
My tensorflow is 1.4 and I used python3 and 2.

`inputs_=tf.placeholder(tf.float32,[*im_size])`

PS. in MNIST dataset since there is no folder of checckpoints it will give us error. you can add a comman to create that folder first and then save it.

I would appreciate if you could help me with this.

**Comment by dataplayer12** [comment]
Hi, thanks for your comment. The code runs okay for me (using TensorFlow 1.3). I suggest replacing the line by:
`inputs_=tf.placeholder(tf.float32,imsize)`
Basically, in my code, I am unpacking a tuple and converting it into a list, which is somewhat unnecessary as tf.placeholder can accept tuples. Please note that unpacking tuples is not available in python 2, so this code will not work with python 2, as you said. Thank you for the suggestion about MNIST. I will add it to the code. Let me know if this fix works for you.

**Comment by jahaniam** [comment]
Thansk. It works now.
